### ISSUE TITLE
Garbage Subdomains from API

### ISSUE THREAD

**Issue by TheTechromancer** [elmasy-com/elmasy#5]
Hey, first off thanks for making the API, it's been very useful.

I'm not sure if this is the best place to raise issues for the API. But we are running into a large quantity of garbage data -- mainly unresolved/nonexistent subdomains.

I figured you might already be aware of this but anyway let me know if you need any more data.

Thanks

**Comment by g0rbe** [comment]
Hi!

> first off thanks for making the API, it's been very useful.

Thanks!

> But we are running into a large quantity of garbage data -- mainly unresolved/nonexistent subdomains.

The main sources are the Certificate Transparency Logs. We parsed every Log from 2021, so it will probably contains historical/unresolved subdomains.

Keeping this number of data valid is hard, so i let the client do the validation after the query for (like crt.sh). (This must be stated in the website/doc, so this is my bad, sorry for that)
But i working on an endpoint that returns validated results.

Im validating the results on domains i know/control and test for methods to insert invalid subdomains (subdomains that never existed/used), but errors can happen, especially in the early phase of this project.

Subdomain count as an error if never existed (like `invalid.elmasy.com`), but not an error if existed in the past (like `dns.danielgorbe.com`).

For further analysis, please send me the domains you queried. Because of the sensitivity of these data, you can send me via email to `info at elmasy.com`.

Thanks!

**Comment by TheTechromancer** [comment]
No worries. An example of a misbehaving domain is `exclaimer.cloud`.

![image](https://github.com/elmasy-com/elmasy/assets/20261699/b91ae0d4-1e34-41c8-8c0a-33d1eaf1ddb9)

**Comment by g0rbe** [comment]
For `exclaimer.cloud` check: https://crt.sh/?q=exclaimer.cloud
On 2018-05-24, 13 new CT Log entries were created with similar format.
Based on that and the time elapsed since then, the number of entries in the DB is realistic.
That's what i call *historical subdomains*.

I don't want to clean these entries, because if 1 person find these historical subdomains useful, i will be more than happy.

You are right, returning every known subdomain is not so useful for most. I came up with a solution for you in the next days.

**Comment by g0rbe** [comment]
Sorry for the delay!

I improved the DB and added new functionalities. It took some time to test/debug and the update is still running.

A new parameter (`days`) added to the lookup endpoint. It filters the result to subdomains that have a valid DNS record in the previous `n` days.

API doc: https://columbus.elmasy.com/swagger/#/domain/get_api_lookup__domain_

What do you think?

**Comment by TheTechromancer** [comment]
This looks awesome! I have one question though. How often are the timestamps updated? E.g. if they're updated every week I'd probably want to say `days=7` to make sure I didn't miss any.

**Comment by g0rbe** [comment]
It heavily depends on the usage on service/domain.

1. If a domain found in a certificate transparency log, the records will be updated for the domain.
2. If domain used in `/api/lookup`, then the domain and its subdomains will be updated **IF** the domain is found in the database (eg.: `/api/lookup/elmasy.com` will update the records of `elmasy.com`, `columbus.elmasy.com`, `blog.elmasy.com`, etc...).
3. The lookup endpoint will save the domain in the `topList` if found and to `notFound` if not found. Multiple servers iterating over the  `topList` to keep the "popular" domains (and its subdomains) up to date. 
4. If a domain used in `/api/history`, then the domain (*only this domain*) will be updated, the result doesn't matter(maybe the records are not found because never updated) (eg.: `/api/history/blog.elmasy.com` will update the records of `blog.elmasy.com`, but not of `columbus.elmasy.com`).
5. The DNS server will updates the records of the domain in the question **IF**  valid answer returned (eg.: `dig blog.elmasy.com` will update the records only for `blog.elmasy.com`). Using our DNS server is the most effective and easiest way to contribute to the project.
6. Updating random selected domains. Not very effective, probably will be trashed.

Interactions with the service will trigger an update on the records, so i you not found something, wait a little and retry. (depends on the size of the domain and the subdomains, updating exclaimer.cloud will take much more time to update than elmasy.com)

I chose this way, because iterating over the whole DB will be an eternity.

Example:
Trigger an update on blog:
```bash
curl 'https://columbus.elmasy.com/api/history/blog.elmasy.com'
```

Trigger an update on elmasy.com and on its subdomains:
```bash
curl 'https://columbus.elmasy.com/api/lookup/elmasy.com'
```

I hope i explained how updates working.

Because you are processing the result, i suggest `days=365` or `days=0` in the beginning, `days=7` is too low.

**Comment by TheTechromancer** [comment]
Wow, I can see you put a lot of work into this. Thank you. I'll test the new changes and keep you posted. 🙏

**Comment by g0rbe** [comment]
Thanks! I really appreciate that.

**Comment by TheTechromancer** [comment]
This makes a big difference. The results look much better now. Thanks!
